steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_PATH}", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_PATH}"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - compute
      - ssh
      - ${_VM_NAME}
      - "--zone=${_ZONE}"
      - "--command=sudo docker pull ${_IMAGE_PATH} && sudo docker rm -f app || true && sudo docker run -d --name app -p ${_CONTAINER_PORT}:${_CONTAINER_PORT} ${_IMAGE_PATH}"

substitutions:
  _IMAGE_PATH="us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}"
  _VM_NAME="${_VM}"
  _ZONE="${_ZONE}"
  _CONTAINER_PORT="${_PORT}"
  
options:
  logging: CLOUD_LOGGING_ONLY
